# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QPushButton, QLabel


class Ui_MainWindow(object):
    def start_yolact(self):
        os.system('python yolact.py')

    def start_rvos(self):
        os.system('python rvos.py')

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 500)
        MainWindow.resize(800, 500)
        MainWindow.setMinimumSize(800, 500)
        MainWindow.setMaximumSize(800, 500)
        MainWindow.setWindowTitle("Sperm segmentation analysis")
        MainWindow.setWindowIcon(QIcon('ivf.png'))

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # Main YOLACT button
        
        self.yolact_button = QPushButton("YOLACT", self.centralwidget)
        self.yolact_button.setGeometry(50, 250, 251, 101)
        self.yolact_button.setObjectName("yolact")
        self.yolact_button.clicked.connect(self.start_yolact)

        # Main RVOS button

        self.rvos_button = QPushButton("RVOS", self.centralwidget)
        self.rvos_button.setGeometry(450, 250, 251, 101)
        self.rvos_button.setObjectName("rvos")
        self.rvos_button.clicked.connect(self.start_rvos)

        # Main label - title

        self.label = QLabel("Analysis of the possibility of sperm segmentation on\n"
"video recordings using machine learning methods", self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 100, 291, 71))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")


        MainWindow.setCentralWidget(self.centralwidget)
        # self.menubar = QMenuBar(MainWindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 566, 21))
        # self.menubar.setObjectName("menubar")
        # MainWindow.setMenuBar(self.menubar)
        # self.statusbar = QStatusBar(MainWindow)
        # self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
